export interface Topic {
  index: number;
  slug: string;
  level: "기초편" | "중급편" | "고급편";
  category: "before" | "bidding" | "after" | "tax" | "law" | "ai";
  title: string;
  keywords: string;
  meta_description: string;
}

export const allTopics: Topic[] = [
  // ── 기초편 43개 ──────────────────────────────────────
  {
    index: 1, slug: "basic-001", level: "기초편", category: "before",
    title: "재테크 완전 초보 가이드: 월급쟁이도 부자 될 수 있다",
    keywords: "재테크입문,부자되는법,월급쟁이재테크",
    meta_description: "재테크를 처음 시작하는 직장인을 위한 완전 초보 가이드. 어디서부터 시작해야 할지 막막한 분들을 위해 핵심만 정리했습니다.",
  },
  {
    index: 2, slug: "basic-002", level: "기초편", category: "before",
    title: "통장 쪼개기 전략: 돈이 모이는 계좌 관리법",
    keywords: "통장쪼개기,계좌관리,돈모으기",
    meta_description: "월급 받자마자 돈이 사라지는 이유와 통장 쪼개기로 자동 저축하는 방법을 알아봅니다.",
  },
  {
    index: 3, slug: "basic-003", level: "기초편", category: "before",
    title: "비상금 만들기: 재테크 시작 전 반드시 해야 할 일",
    keywords: "비상금,비상자금,생활비3개월",
    meta_description: "투자를 시작하기 전 반드시 비상금을 먼저 마련해야 하는 이유와 올바른 비상금 규모를 설명합니다.",
  },
  {
    index: 4, slug: "basic-004", level: "기초편", category: "before",
    title: "신용점수 올리는 방법: 대출과 투자의 기초",
    keywords: "신용점수,신용등급,신용관리",
    meta_description: "신용점수가 재테크에 미치는 영향과 점수를 올리는 실질적인 방법을 단계별로 알려드립니다.",
  },
  {
    index: 5, slug: "basic-005", level: "기초편", category: "before",
    title: "재무 목표 설정하는 법: 막연한 꿈을 숫자로 바꾸기",
    keywords: "재무목표,목표설정,재테크계획",
    meta_description: "막연하게 '부자가 되고 싶다'는 생각을 구체적인 숫자와 기간이 있는 재무 목표로 전환하는 방법.",
  },
  {
    index: 6, slug: "basic-006", level: "기초편", category: "before",
    title: "가계부 쓰는 법: 지출 파악이 재테크의 첫걸음",
    keywords: "가계부,지출관리,소비패턴",
    meta_description: "가계부를 꾸준히 쓰기 어려운 이유와 앱을 활용해 3분 만에 끝내는 현실적인 가계부 방법.",
  },
  {
    index: 7, slug: "basic-007", level: "기초편", category: "before",
    title: "직장인 연말정산 완전 정복: 세금 환급 최대화",
    keywords: "연말정산,세금환급,소득공제",
    meta_description: "연말정산에서 최대한 많이 돌려받는 방법. 놓치기 쉬운 공제 항목과 13월의 월급 만드는 전략.",
  },
  {
    index: 8, slug: "basic-008", level: "기초편", category: "before",
    title: "청약통장 완벽 정리: 내 집 마련의 첫 단추",
    keywords: "청약통장,주택청약,청약점수",
    meta_description: "청약통장 종류와 납입 방법, 청약 점수 높이는 전략까지 내 집 마련을 위한 청약 완전 가이드.",
  },
  {
    index: 9, slug: "basic-009", level: "기초편", category: "before",
    title: "금융 상품 종류 총정리: 예금, 적금, 펀드, ETF 차이",
    keywords: "금융상품비교,예금적금,펀드ETF",
    meta_description: "예금, 적금, 펀드, ETF의 차이점과 각각 어떤 상황에 적합한지 쉽게 비교 정리했습니다.",
  },
  {
    index: 10, slug: "basic-010", level: "기초편", category: "before",
    title: "인플레이션이란? 돈 가치가 떨어지는 이유와 대응법",
    keywords: "인플레이션,물가상승,화폐가치",
    meta_description: "인플레이션이 우리 자산에 미치는 영향과 물가 상승 시대에 자산을 지키는 투자 방법.",
  },
  {
    index: 11, slug: "basic-011", level: "기초편", category: "bidding",
    title: "주식 투자 기초: 처음 주식 사는 법 A to Z",
    keywords: "주식투자입문,주식계좌개설,첫주식",
    meta_description: "주식 계좌 개설부터 첫 매수까지 주식 투자 완전 초보를 위한 단계별 가이드.",
  },
  {
    index: 12, slug: "basic-012", level: "기초편", category: "bidding",
    title: "ETF 투자 입문: 개별주식보다 안전하게 시작하기",
    keywords: "ETF투자,ETF란,ETF입문",
    meta_description: "ETF가 무엇인지, 왜 개별주식보다 초보자에게 적합한지 그리고 국내 ETF 시작하는 방법.",
  },
  {
    index: 13, slug: "basic-013", level: "기초편", category: "bidding",
    title: "적립식 투자란? 매달 조금씩 투자하는 방법",
    keywords: "적립식투자,DCA,정액투자",
    meta_description: "한 번에 목돈을 투자하는 것보다 매달 일정 금액을 투자하는 적립식 전략의 장점과 실전 방법.",
  },
  {
    index: 14, slug: "basic-014", level: "기초편", category: "bidding",
    title: "코스피와 코스닥: 한국 증시 기초 상식",
    keywords: "코스피,코스닥,한국주식시장",
    meta_description: "코스피와 코스닥의 차이, 시장 구조를 이해하면 투자 선택이 쉬워집니다.",
  },
  {
    index: 15, slug: "basic-015", level: "기초편", category: "bidding",
    title: "배당주 투자: 월급 외 현금흐름 만들기",
    keywords: "배당주,배당투자,패시브인컴",
    meta_description: "정기적으로 배당을 지급하는 주식에 투자해 월급 이외의 수입을 만드는 방법.",
  },
  {
    index: 16, slug: "basic-016", level: "기초편", category: "bidding",
    title: "국내 ETF vs 해외 ETF: 어디에 투자할까",
    keywords: "국내ETF,해외ETF,ETF비교",
    meta_description: "국내 상장 ETF와 해외 직접 투자 ETF의 세금, 수수료, 접근성 차이를 비교합니다.",
  },
  {
    index: 17, slug: "basic-017", level: "기초편", category: "bidding",
    title: "S&P500 ETF 투자: 미국 시장에 쉽게 투자하기",
    keywords: "SP500,미국ETF,VOO,IVV",
    meta_description: "미국 대표 지수 S&P500에 투자하는 ETF 종류와 국내에서 쉽게 투자하는 방법.",
  },
  {
    index: 18, slug: "basic-018", level: "기초편", category: "bidding",
    title: "채권 투자란? 주식보다 안전한 투자 방법",
    keywords: "채권투자,채권이란,안전자산",
    meta_description: "채권이 무엇인지, 주식과 어떻게 다른지, 그리고 채권 투자로 포트폴리오 안정성 높이는 방법.",
  },
  {
    index: 19, slug: "basic-019", level: "기초편", category: "after",
    title: "포트폴리오란? 투자 분산의 중요성",
    keywords: "포트폴리오,분산투자,자산배분",
    meta_description: "달걀을 한 바구니에 담지 말라는 투자 원칙. 포트폴리오 구성의 기초와 분산투자 방법.",
  },
  {
    index: 20, slug: "basic-020", level: "기초편", category: "after",
    title: "재테크 계좌 종류: ISA, IRP, 연금저축 완전 비교",
    keywords: "ISA계좌,IRP계좌,연금저축,절세계좌",
    meta_description: "세금 혜택이 있는 주요 투자 계좌 ISA, IRP, 연금저축의 차이점과 활용법 비교.",
  },
  {
    index: 21, slug: "basic-021", level: "기초편", category: "after",
    title: "ISA 계좌 완벽 정리: 세금 없이 투자하는 방법",
    keywords: "ISA계좌,개인종합자산관리계좌,비과세",
    meta_description: "ISA 계좌로 주식, 펀드, ETF를 세금 없이 투자하는 방법과 만기 활용 전략.",
  },
  {
    index: 22, slug: "basic-022", level: "기초편", category: "after",
    title: "IRP 계좌 활용법: 노후 준비와 세액공제 동시에",
    keywords: "IRP,개인형퇴직연금,세액공제",
    meta_description: "IRP 계좌로 연 900만원까지 세액공제 받으면서 노후를 준비하는 현명한 방법.",
  },
  {
    index: 23, slug: "basic-023", level: "기초편", category: "after",
    title: "손절매란? 손실을 줄이는 투자 원칙",
    keywords: "손절매,손절,투자원칙,리스크관리",
    meta_description: "성공적인 투자자가 반드시 지키는 손절매 원칙과 감정에 흔들리지 않는 투자 방법.",
  },
  {
    index: 24, slug: "basic-024", level: "기초편", category: "tax",
    title: "직장인이 꼭 알아야 할 세금 종류 총정리",
    keywords: "직장인세금,소득세,4대보험",
    meta_description: "월급에서 떼이는 세금의 종류와 계산 방식, 합법적으로 줄이는 방법을 알아봅니다.",
  },
  {
    index: 25, slug: "basic-025", level: "기초편", category: "tax",
    title: "소득세 절세 방법: 합법적으로 세금 줄이기",
    keywords: "소득세절세,세금줄이기,절세전략",
    meta_description: "직장인이 합법적으로 소득세를 줄이는 방법. 소득공제와 세액공제의 차이부터 실전 절세 팁.",
  },
  {
    index: 26, slug: "basic-026", level: "기초편", category: "tax",
    title: "투자 수익에 붙는 세금: 주식, 펀드, 부동산 비교",
    keywords: "투자세금,양도소득세,배당소득세",
    meta_description: "주식, 펀드, 부동산 각 투자 상품에서 수익이 발생할 때 붙는 세금의 종류와 계산법.",
  },
  {
    index: 27, slug: "basic-027", level: "기초편", category: "tax",
    title: "연금저축 세액공제: 얼마나 돌려받을 수 있나",
    keywords: "연금저축세액공제,연금저축펀드,노후절세",
    meta_description: "연금저축계좌에 납입하면 얼마나 세금을 돌려받을 수 있는지 소득 구간별로 계산합니다.",
  },
  {
    index: 28, slug: "basic-028", level: "기초편", category: "law",
    title: "금융소비자 보호법: 투자자가 알아야 할 권리",
    keywords: "금융소비자보호법,투자자권리,금융민원",
    meta_description: "금융소비자 보호법이 만들어진 이유와 투자자로서 내가 받을 수 있는 보호와 권리.",
  },
  {
    index: 29, slug: "basic-029", level: "기초편", category: "law",
    title: "불법 다단계와 합법 투자: 구별하는 방법",
    keywords: "불법다단계,투자사기,합법투자",
    meta_description: "투자 사기와 합법적인 투자를 구별하는 방법. 실제 사례로 배우는 불법 금융 상품 피하기.",
  },
  {
    index: 30, slug: "basic-030", level: "기초편", category: "law",
    title: "증권사 계좌 개설 전 알아야 할 약관 핵심",
    keywords: "증권사계좌,MTS,약관,수수료",
    meta_description: "증권사 계좌를 개설하기 전 반드시 확인해야 할 수수료 구조와 약관의 핵심 내용.",
  },
  {
    index: 31, slug: "basic-031", level: "기초편", category: "ai",
    title: "AI로 주식 공부하는 방법: 초보자 활용법",
    keywords: "AI주식공부,챗GPT투자,AI재테크",
    meta_description: "AI 도구를 활용해 재테크 지식을 빠르게 습득하고 투자 아이디어를 발굴하는 방법.",
  },
  {
    index: 32, slug: "basic-032", level: "기초편", category: "ai",
    title: "재테크 앱 추천: 자산 관리를 돕는 스마트폰 앱",
    keywords: "재테크앱,자산관리앱,투자앱추천",
    meta_description: "자산 현황 파악부터 투자 정보 수집까지 직장인 재테크를 도와주는 앱 추천 목록.",
  },
  {
    index: 33, slug: "basic-033", level: "기초편", category: "ai",
    title: "챗GPT로 투자 공부하기: 실전 프롬프트 가이드",
    keywords: "챗GPT투자,AI투자공부,ChatGPT재테크",
    meta_description: "챗GPT를 활용해 재무제표 분석, 투자 용어 학습, 시장 분석을 빠르게 하는 프롬프트 모음.",
  },
  {
    index: 34, slug: "basic-034", level: "기초편", category: "before",
    title: "재테크 실패 원인 TOP 5: 초보자가 꼭 피해야 할 것들",
    keywords: "재테크실패,투자실패,초보자실수",
    meta_description: "재테크를 시작했지만 실패하는 가장 흔한 이유 5가지와 그것을 피하는 방법.",
  },
  {
    index: 35, slug: "basic-035", level: "기초편", category: "before",
    title: "저축률 높이는 방법: 월급의 몇 %를 저축해야 할까",
    keywords: "저축률,저축습관,월급저축",
    meta_description: "적정 저축률과 저축을 늘리는 현실적인 방법. 지출을 줄이지 않고 저축을 늘리는 전략.",
  },
  {
    index: 36, slug: "basic-036", level: "기초편", category: "bidding",
    title: "리밸런싱이란? 투자 비중 조정하는 방법",
    keywords: "리밸런싱,자산비중조정,포트폴리오관리",
    meta_description: "자산 비중이 목표에서 벗어났을 때 조정하는 리밸런싱. 언제, 어떻게 해야 하는지 알아봅니다.",
  },
  {
    index: 37, slug: "basic-037", level: "기초편", category: "bidding",
    title: "공모주 청약 방법: 상장 전 주식 사는 법",
    keywords: "공모주청약,IPO,공모주투자",
    meta_description: "기업이 상장하기 전 공모주를 청약해 수익을 내는 방법과 청약 참여 시 주의사항.",
  },
  {
    index: 38, slug: "basic-038", level: "기초편", category: "after",
    title: "연금저축펀드 투자법: 노후와 절세 동시 공략",
    keywords: "연금저축펀드,연금계좌투자,노후준비",
    meta_description: "연금저축펀드 계좌에서 ETF를 사는 방법과 세액공제 혜택을 최대로 활용하는 전략.",
  },
  {
    index: 39, slug: "basic-039", level: "기초편", category: "tax",
    title: "금융투자소득세 완벽 정리: 투자자가 알아야 할 변화",
    keywords: "금융투자소득세,금투세,주식세금",
    meta_description: "금융투자소득세의 개념, 과세 기준, 투자 전략에 미치는 영향을 쉽게 풀어 설명합니다.",
  },
  {
    index: 40, slug: "basic-040", level: "기초편", category: "law",
    title: "투자 사기 유형과 예방법: 실제 사례로 배우기",
    keywords: "투자사기,금융사기예방,사기피해",
    meta_description: "실제로 발생한 투자 사기 유형과 패턴을 알고 피해를 예방하는 방법.",
  },
  {
    index: 41, slug: "basic-041", level: "기초편", category: "ai",
    title: "로보어드바이저란? AI가 대신 투자해주는 서비스",
    keywords: "로보어드바이저,AI투자,자동투자",
    meta_description: "AI가 자동으로 자산을 배분하고 투자해주는 로보어드바이저의 장단점과 주요 서비스 비교.",
  },
  {
    index: 42, slug: "basic-042", level: "기초편", category: "before",
    title: "종잣돈 1000만원 모으는 방법: 1년 안에 가능한가",
    keywords: "종잣돈,1000만원모으기,목돈마련",
    meta_description: "1년 안에 종잣돈 1000만원을 모으는 구체적인 방법과 월별 저축 계획.",
  },
  {
    index: 43, slug: "basic-043", level: "기초편", category: "bidding",
    title: "테마주 투자 주의사항: 급등주에 흔들리지 않는 법",
    keywords: "테마주,급등주,묻지마투자",
    meta_description: "테마주와 급등주에 투자할 때 발생하는 위험과 감정적 투자를 피하는 원칙.",
  },

  // ── 중급편 43개 ──────────────────────────────────────
  {
    index: 44, slug: "mid-001", level: "중급편", category: "before",
    title: "투자 성향 파악하기: 나는 어떤 투자자인가",
    keywords: "투자성향,투자자유형,위험선호도",
    meta_description: "자신의 투자 성향을 정확히 파악해야 올바른 자산 배분이 가능합니다. 투자 성향 자가진단 방법.",
  },
  {
    index: 45, slug: "mid-002", level: "중급편", category: "before",
    title: "자산 배분 전략: 주식, 채권, 현금 비율 설정법",
    keywords: "자산배분,포트폴리오비율,투자전략",
    meta_description: "나이와 목표에 맞는 자산 배분 비율을 설정하는 방법과 대표적인 자산 배분 모델 소개.",
  },
  {
    index: 46, slug: "mid-003", level: "중급편", category: "before",
    title: "경제 지표 읽는 법: GDP, 금리, 환율의 관계",
    keywords: "경제지표,GDP,금리환율,거시경제",
    meta_description: "투자에 영향을 미치는 핵심 경제 지표들의 의미와 서로 어떻게 연결되는지 알아봅니다.",
  },
  {
    index: 47, slug: "mid-004", level: "중급편", category: "before",
    title: "금리와 주가의 관계: 기준금리 변화가 투자에 미치는 영향",
    keywords: "금리주가관계,기준금리,금리인상인하",
    meta_description: "한국은행의 기준금리 결정이 주식, 채권, 부동산 시장에 어떤 영향을 미치는지 분석합니다.",
  },
  {
    index: 48, slug: "mid-005", level: "중급편", category: "before",
    title: "달러 투자 방법: 환율로 수익 내는 전략",
    keywords: "달러투자,환율투자,달러예금",
    meta_description: "달러 예금, 달러 ETF, 달러 RP 등 다양한 방법으로 달러에 투자해 환차익을 노리는 전략.",
  },
  {
    index: 49, slug: "mid-006", level: "중급편", category: "bidding",
    title: "가치투자란? 저평가 주식 찾는 방법",
    keywords: "가치투자,저평가주식,워런버핏",
    meta_description: "워런 버핏의 투자 철학 가치투자의 핵심 원칙과 실제로 저평가된 주식을 찾는 방법.",
  },
  {
    index: 50, slug: "mid-007", level: "중급편", category: "bidding",
    title: "PER, PBR, ROE: 주식 가치 분석 지표 완전 정복",
    keywords: "PER,PBR,ROE,주식분석지표",
    meta_description: "주식 투자에서 가장 많이 사용되는 밸류에이션 지표 PER, PBR, ROE의 의미와 활용법.",
  },
  {
    index: 51, slug: "mid-008", level: "중급편", category: "bidding",
    title: "배당성장주 투자: 매년 배당이 늘어나는 주식 고르기",
    keywords: "배당성장주,배당귀족,배당성장투자",
    meta_description: "단순 고배당주보다 배당을 지속적으로 늘리는 배당성장주가 장기 투자에 유리한 이유.",
  },
  {
    index: 52, slug: "mid-009", level: "중급편", category: "bidding",
    title: "섹터 ETF 투자: 반도체, 헬스케어, 2차전지 선택법",
    keywords: "섹터ETF,반도체ETF,테마ETF",
    meta_description: "특정 산업에 집중 투자하는 섹터 ETF의 종류와 경기 사이클에 따른 섹터 선택 방법.",
  },
  {
    index: 53, slug: "mid-010", level: "중급편", category: "bidding",
    title: "레버리지 ETF 위험성과 활용법: 수익률 2배의 함정",
    keywords: "레버리지ETF,2배ETF,변동성붕괴",
    meta_description: "레버리지 ETF가 장기 보유 시 왜 손실이 날 수 있는지와 단기 활용 시 주의사항.",
  },
  {
    index: 54, slug: "mid-011", level: "중급편", category: "bidding",
    title: "국내 리츠 투자: 소액으로 부동산 임대 수익 받기",
    keywords: "리츠투자,REIT,부동산간접투자",
    meta_description: "소액으로 부동산에 투자해 임대 수익을 받는 리츠의 종류와 투자 방법.",
  },
  {
    index: 55, slug: "mid-012", level: "중급편", category: "bidding",
    title: "해외주식 직접 투자: 미국주식 매매 완전 정복",
    keywords: "미국주식,해외주식투자,나스닥투자",
    meta_description: "국내 증권사 앱에서 미국 주식을 직접 매매하는 방법과 환전, 세금 처리까지 전체 가이드.",
  },
  {
    index: 56, slug: "mid-013", level: "중급편", category: "bidding",
    title: "성장주 vs 가치주: 어느 쪽이 더 유리한가",
    keywords: "성장주,가치주,투자스타일비교",
    meta_description: "성장주와 가치주의 차이, 각각의 장단점, 그리고 금리 환경에 따른 유불리 분석.",
  },
  {
    index: 57, slug: "mid-014", level: "중급편", category: "bidding",
    title: "채권 ETF 포트폴리오에 넣는 방법",
    keywords: "채권ETF,채권투자,안전자산",
    meta_description: "주식 포트폴리오의 변동성을 줄이기 위해 채권 ETF를 추가하는 방법과 비중 설정.",
  },
  {
    index: 58, slug: "mid-015", level: "중급편", category: "bidding",
    title: "원자재 투자: 금, 은, 원유 ETF 활용법",
    keywords: "금투자,원자재투자,금ETF",
    meta_description: "인플레이션 헤지와 분산투자를 위한 금, 은, 원유 ETF 투자 방법과 비중 설정.",
  },
  {
    index: 59, slug: "mid-016", level: "중급편", category: "after",
    title: "코어-새틀라이트 전략: 안정성과 수익성 동시 추구",
    keywords: "코어새틀라이트,투자전략,포트폴리오전략",
    meta_description: "핵심 자산과 위성 자산으로 나눠 안정성을 유지하면서 추가 수익을 추구하는 전략.",
  },
  {
    index: 60, slug: "mid-017", level: "중급편", category: "after",
    title: "배당 포트폴리오 만들기: 월 100만원 배당받기 목표",
    keywords: "배당포트폴리오,월배당,배당수익",
    meta_description: "월 100만원의 배당 수익을 위해 필요한 투자금과 포트폴리오 구성 방법.",
  },
  {
    index: 61, slug: "mid-018", level: "중급편", category: "after",
    title: "장기 투자 vs 단기 투자: 어느 쪽이 더 유리한가",
    keywords: "장기투자,단기투자,투자기간",
    meta_description: "데이터로 보는 장기 투자와 단기 투자의 실제 수익률 비교와 각각의 적합한 상황.",
  },
  {
    index: 62, slug: "mid-019", level: "중급편", category: "after",
    title: "투자 심리 관리: 공포와 탐욕을 이기는 방법",
    keywords: "투자심리,감정투자,공포탐욕지수",
    meta_description: "주식 시장에서 실패하는 대부분의 원인은 심리적 문제입니다. 투자 심리를 관리하는 방법.",
  },
  {
    index: 63, slug: "mid-020", level: "중급편", category: "after",
    title: "MDD(최대낙폭) 이해하기: 내 포트폴리오 위험 측정법",
    keywords: "MDD,최대낙폭,리스크측정",
    meta_description: "포트폴리오의 위험을 측정하는 MDD(최대낙폭) 개념과 자신의 위험 허용 범위 설정법.",
  },
  {
    index: 64, slug: "mid-021", level: "중급편", category: "after",
    title: "세금 효율적인 포트폴리오 구성: 계좌별 투자 전략",
    keywords: "절세포트폴리오,계좌별투자,세금효율",
    meta_description: "ISA, IRP, 연금저축, 일반계좌에 어떤 상품을 넣어야 세금을 최소화할 수 있는지 전략.",
  },
  {
    index: 65, slug: "mid-022", level: "중급편", category: "after",
    title: "글로벌 분산투자: 미국, 유럽, 신흥국 비중 설정",
    keywords: "글로벌분산투자,해외분산,신흥국투자",
    meta_description: "미국 편중 투자의 위험과 글로벌 분산 투자 시 국가별 비중을 설정하는 방법.",
  },
  {
    index: 66, slug: "mid-023", level: "중급편", category: "after",
    title: "복리의 마법: 시간이 돈을 불리는 원리",
    keywords: "복리투자,72법칙,장기복리",
    meta_description: "아인슈타인이 세계 8대 불가사의라 불렀다는 복리. 실제로 어떻게 자산을 불리는지 계산.",
  },
  {
    index: 67, slug: "mid-024", level: "중급편", category: "tax",
    title: "금융소득종합과세 피하는 방법: 2000만원 기준선 관리",
    keywords: "금융소득종합과세,2000만원,이자배당소득",
    meta_description: "금융소득이 연 2000만원을 초과하면 종합과세 대상이 됩니다. 기준선을 관리하는 절세 전략.",
  },
  {
    index: 68, slug: "mid-025", level: "중급편", category: "tax",
    title: "해외주식 양도소득세 신고 방법: 250만원 공제 활용",
    keywords: "해외주식세금,양도소득세신고,해외주식절세",
    meta_description: "해외주식에서 수익이 났을 때 양도소득세 신고 방법과 연간 250만원 공제를 활용하는 전략.",
  },
  {
    index: 69, slug: "mid-026", level: "중급편", category: "tax",
    title: "ISA 계좌 만기 활용법: 세금 없이 연금 전환하기",
    keywords: "ISA만기,ISA연금전환,ISA절세",
    meta_description: "ISA 계좌 만기 시 연금저축으로 전환해 추가 세액공제를 받는 방법과 주의사항.",
  },
  {
    index: 70, slug: "mid-027", level: "중급편", category: "tax",
    title: "배당소득세 절세 전략: 계좌별 세금 차이 완전 정리",
    keywords: "배당소득세,배당세금절세,비과세계좌",
    meta_description: "일반계좌, ISA, 연금계좌별로 배당소득에 붙는 세금이 어떻게 다른지 비교 분석.",
  },
  {
    index: 71, slug: "mid-028", level: "중급편", category: "tax",
    title: "부동산 취득세, 양도세 계산법: 투자 전 필수 확인",
    keywords: "취득세,양도소득세,부동산세금계산",
    meta_description: "부동산 투자 시 발생하는 취득세와 양도소득세 계산법과 절세 전략.",
  },
  {
    index: 72, slug: "mid-029", level: "중급편", category: "law",
    title: "투자자문업과 투자일임업: 자산 위탁 전 알아야 할 법",
    keywords: "투자자문,투자일임,자산위탁",
    meta_description: "투자 자문과 일임 서비스를 이용할 때 알아야 할 법적 기준과 피해 예방법.",
  },
  {
    index: 73, slug: "mid-030", level: "중급편", category: "law",
    title: "공시 제도 이해: 기업 공시 읽는 방법",
    keywords: "기업공시,사업보고서,전자공시시스템",
    meta_description: "DART(전자공시시스템)에서 기업 공시를 찾고 투자에 활용하는 방법.",
  },
  {
    index: 74, slug: "mid-031", level: "중급편", category: "law",
    title: "내부자 거래 규정: 합법과 불법의 경계선",
    keywords: "내부자거래,미공개정보,불공정거래",
    meta_description: "내부자 거래란 무엇이고 어디까지가 합법인지, 투자자가 알아야 할 규정.",
  },
  {
    index: 75, slug: "mid-032", level: "중급편", category: "law",
    title: "금융 분쟁 조정 제도: 피해 발생 시 대응 방법",
    keywords: "금융분쟁조정,금융민원,금융피해구제",
    meta_description: "금융 거래에서 피해가 발생했을 때 금융감독원에 분쟁 조정을 신청하는 방법.",
  },
  {
    index: 76, slug: "mid-033", level: "중급편", category: "ai",
    title: "퀀트 투자 입문: 데이터로 종목 선정하는 방법",
    keywords: "퀀트투자,데이터투자,팩터투자",
    meta_description: "감이 아닌 데이터로 투자하는 퀀트 투자의 기본 개념과 일반 투자자가 적용하는 방법.",
  },
  {
    index: 77, slug: "mid-034", level: "중급편", category: "ai",
    title: "AI 투자 분석 도구 활용법: 재무제표 분석 자동화",
    keywords: "AI재무분석,투자분석자동화,AI도구활용",
    meta_description: "AI를 활용해 기업의 재무제표를 빠르게 분석하고 투자 판단에 활용하는 방법.",
  },
  {
    index: 78, slug: "mid-035", level: "중급편", category: "ai",
    title: "파이썬으로 주식 데이터 분석: 투자자를 위한 기초",
    keywords: "파이썬주식,주식데이터분석,파이썬투자",
    meta_description: "프로그래밍 경험이 없어도 파이썬으로 주식 데이터를 분석하는 기초 방법.",
  },
  {
    index: 79, slug: "mid-036", level: "중급편", category: "ai",
    title: "AI 뉴스 분석으로 투자 판단하기: 감성 분석 활용법",
    keywords: "AI뉴스분석,감성분석,투자신호",
    meta_description: "AI를 활용해 수많은 금융 뉴스에서 투자 신호를 찾아내는 감성 분석 방법.",
  },
  {
    index: 80, slug: "mid-037", level: "중급편", category: "before",
    title: "부동산 투자 vs 주식 투자: 1억으로 어디에 투자할까",
    keywords: "부동산vs주식,1억투자,투자비교",
    meta_description: "1억원을 부동산에 투자할지 주식에 투자할지 수익률, 세금, 유동성 측면에서 비교 분석.",
  },
  {
    index: 81, slug: "mid-038", level: "중급편", category: "bidding",
    title: "분할매수 전략: 한 번에 사지 않고 나눠 사는 이유",
    keywords: "분할매수,매수전략,DCA분할",
    meta_description: "한 번에 매수하는 것보다 나눠서 사는 분할매수가 투자 리스크를 줄이는 이유.",
  },
  {
    index: 82, slug: "mid-039", level: "중급편", category: "bidding",
    title: "공매도란? 하락장에서 수익 내는 방법",
    keywords: "공매도,하락투자,숏투자",
    meta_description: "주가가 하락할 때 오히려 수익을 낼 수 있는 공매도의 원리와 개인 투자자가 활용하는 방법.",
  },
  {
    index: 83, slug: "mid-040", level: "중급편", category: "after",
    title: "투자 일기 쓰는 법: 나만의 투자 원칙 만들기",
    keywords: "투자일기,투자원칙,투자기록",
    meta_description: "성공한 투자자들이 공통적으로 하는 투자 일기 쓰는 방법과 나만의 투자 원칙 정립.",
  },
  {
    index: 84, slug: "mid-041", level: "중급편", category: "tax",
    title: "증여세 활용한 자산 이전: 자녀에게 합법적으로 자산 물려주기",
    keywords: "증여세,자산증여,절세증여",
    meta_description: "자녀에게 자산을 물려줄 때 증여세를 합법적으로 최소화하는 방법과 증여 한도.",
  },
  {
    index: 85, slug: "mid-042", level: "중급편", category: "law",
    title: "금융 계약서 꼼꼼히 읽는 법: 놓치기 쉬운 독소 조항",
    keywords: "금융계약서,독소조항,금융계약주의",
    meta_description: "금융 상품 가입 시 계약서에서 반드시 확인해야 할 독소 조항과 체크 포인트.",
  },
  {
    index: 86, slug: "mid-043", level: "중급편", category: "ai",
    title: "AI와 함께 포트폴리오 점검하기: 투자 전략 수립",
    keywords: "AI포트폴리오,AI투자전략,챗봇투자",
    meta_description: "AI 도구를 활용해 현재 포트폴리오를 점검하고 개선 방향을 찾는 실전 방법.",
  },

  // ── 고급편 44개 ──────────────────────────────────────
  {
    index: 87, slug: "adv-001", level: "고급편", category: "before",
    title: "거시경제 분석으로 투자 타이밍 잡기",
    keywords: "거시경제분석,투자타이밍,경기분석",
    meta_description: "경기 선행지수, 장단기 금리차 등 거시경제 지표를 분석해 투자 타이밍을 잡는 방법.",
  },
  {
    index: 88, slug: "adv-002", level: "고급편", category: "before",
    title: "자산 배분 모델 비교: 올웨더, 영구 포트폴리오, 60/40",
    keywords: "올웨더포트폴리오,영구포트폴리오,자산배분모델",
    meta_description: "레이 달리오의 올웨더, 해리 브라운의 영구 포트폴리오, 전통적 60/40 전략 비교 분석.",
  },
  {
    index: 89, slug: "adv-003", level: "고급편", category: "before",
    title: "경기 사이클과 투자: 침체, 회복, 호황, 과열 단계별 전략",
    keywords: "경기사이클,경기순환투자,사이클투자",
    meta_description: "경기 사이클의 4단계를 이해하고 각 단계에 적합한 자산과 섹터에 투자하는 전략.",
  },
  {
    index: 90, slug: "adv-004", level: "고급편", category: "before",
    title: "헤지 전략: 불확실성을 줄이는 고급 투자 기법",
    keywords: "헤지전략,리스크헤지,포트폴리오보호",
    meta_description: "금, 채권, 인버스 ETF 등을 활용해 포트폴리오 하락 위험을 줄이는 헤지 전략.",
  },
  {
    index: 91, slug: "adv-005", level: "고급편", category: "before",
    title: "대안 투자란? 주식·채권 외 투자 방법 총정리",
    keywords: "대안투자,헤지펀드,PEF,실물투자",
    meta_description: "전통적 주식·채권 외에 부동산, 원자재, 사모펀드 등 대안 투자의 종류와 특징.",
  },
  {
    index: 92, slug: "adv-006", level: "고급편", category: "bidding",
    title: "옵션 투자 기초: 콜옵션과 풋옵션 이해하기",
    keywords: "옵션투자,콜옵션,풋옵션,파생상품",
    meta_description: "주식 옵션의 기본 개념, 콜과 풋의 차이, 그리고 실제로 활용하는 기초 전략.",
  },
  {
    index: 93, slug: "adv-007", level: "고급편", category: "bidding",
    title: "공모주 고수익 전략: 청약 경쟁률과 수익률의 관계",
    keywords: "공모주전략,청약경쟁률,공모주수익률",
    meta_description: "공모주 청약에서 수익을 극대화하는 전략. 경쟁률과 실제 수익률의 관계 분석.",
  },
  {
    index: 94, slug: "adv-008", level: "고급편", category: "bidding",
    title: "국채 투자 전략: 금리 하락기에 채권으로 수익 내기",
    keywords: "국채투자,채권투자전략,금리하락",
    meta_description: "기준금리 인하 사이클에서 채권 가격 상승을 이용해 수익을 내는 전략.",
  },
  {
    index: 95, slug: "adv-009", level: "고급편", category: "bidding",
    title: "해외 리츠 투자: 미국 REITs로 달러 배당받기",
    keywords: "미국리츠,해외리츠,달러배당",
    meta_description: "미국 상장 리츠에 직접 투자해 달러 배당을 받는 방법과 대표적인 리츠 종목 분석.",
  },
  {
    index: 96, slug: "adv-010", level: "고급편", category: "bidding",
    title: "섹터 로테이션 전략: 경기에 따라 투자 섹터 바꾸기",
    keywords: "섹터로테이션,경기순환섹터,섹터전략",
    meta_description: "경기 국면에 따라 강세 섹터가 달라지는 원리와 섹터 로테이션 전략으로 수익 내는 방법.",
  },
  {
    index: 97, slug: "adv-011", level: "고급편", category: "bidding",
    title: "인버스 ETF 활용법: 하락장을 기회로 만드는 방법",
    keywords: "인버스ETF,하락장투자,숏ETF",
    meta_description: "주가 하락 시 수익을 내는 인버스 ETF의 원리와 언제, 어떻게 활용해야 하는지.",
  },
  {
    index: 98, slug: "adv-012", level: "고급편", category: "bidding",
    title: "알고리즘 트레이딩 이해: 자동매매 시스템의 원리",
    keywords: "알고리즘트레이딩,자동매매,시스템트레이딩",
    meta_description: "알고리즘 트레이딩이 시장에 미치는 영향과 개인 투자자가 자동매매를 활용하는 방법.",
  },
  {
    index: 99, slug: "adv-013", level: "고급편", category: "bidding",
    title: "소형주 투자 전략: 숨겨진 종목 발굴하기",
    keywords: "소형주투자,중소형주,저평가소형주",
    meta_description: "대형주보다 높은 수익률을 기대할 수 있는 소형주 투자 전략과 종목 발굴 방법.",
  },
  {
    index: 100, slug: "adv-014", level: "고급편", category: "bidding",
    title: "전환사채(CB) 투자: 주식과 채권의 중간 상품",
    keywords: "전환사채,CB투자,메자닌투자",
    meta_description: "주식으로 전환 가능한 전환사채의 구조와 투자 시 고려해야 할 핵심 요소.",
  },
  {
    index: 101, slug: "adv-015", level: "고급편", category: "bidding",
    title: "글로벌 배당 ETF 비교: SCHD, VYM, HDV 완전 분석",
    keywords: "SCHD,VYM,HDV,배당ETF비교",
    meta_description: "미국 대표 배당 ETF SCHD, VYM, HDV의 구성 종목, 수익률, 배당 성장률 비교 분석.",
  },
  {
    index: 102, slug: "adv-016", level: "고급편", category: "after",
    title: "은퇴 포트폴리오 설계: 나이별 자산 배분 변화",
    keywords: "은퇴포트폴리오,연령별자산배분,노후설계",
    meta_description: "30대, 40대, 50대, 은퇴 후 각 시기에 적합한 자산 배분 전략과 포트폴리오 조정 방법.",
  },
  {
    index: 103, slug: "adv-017", level: "고급편", category: "after",
    title: "인출 전략: 은퇴 후 자산을 얼마나 써야 하나 (4% 룰)",
    keywords: "4%룰,인출전략,은퇴자산관리",
    meta_description: "은퇴 후 자산을 고갈 없이 사용하는 인출 전략. 4% 룰의 원리와 한국 상황에 맞는 수정 방법.",
  },
  {
    index: 104, slug: "adv-018", level: "고급편", category: "after",
    title: "세대 간 자산 이전 전략: 장기적 부의 보존법",
    keywords: "세대간자산이전,부의이전,상속증여전략",
    meta_description: "부모에서 자녀로, 자녀에서 손자녀로 이어지는 자산 이전 전략과 절세 방법.",
  },
  {
    index: 105, slug: "adv-019", level: "고급편", category: "after",
    title: "고배당 포트폴리오 최적화: 배당수익률 vs 배당성장률",
    keywords: "고배당최적화,배당수익률,배당성장률비교",
    meta_description: "당장 높은 배당을 원하는 투자자와 장기 성장을 원하는 투자자에게 각각 맞는 전략.",
  },
  {
    index: 106, slug: "adv-020", level: "고급편", category: "after",
    title: "팩터 투자란? 모멘텀, 퀄리티, 사이즈 팩터 활용",
    keywords: "팩터투자,스마트베타,모멘텀팩터",
    meta_description: "시장 초과 수익을 설명하는 팩터들 - 모멘텀, 퀄리티, 사이즈, 밸류 팩터 투자 방법.",
  },
  {
    index: 107, slug: "adv-021", level: "고급편", category: "after",
    title: "ESG 투자: 착한 기업에 투자하면 수익도 날까",
    keywords: "ESG투자,지속가능투자,ESG펀드",
    meta_description: "환경, 사회, 지배구조를 고려한 ESG 투자의 실제 수익률과 장기 전망.",
  },
  {
    index: 108, slug: "adv-022", level: "고급편", category: "after",
    title: "스마트 베타 ETF: 시장 대비 초과 수익을 노리는 방법",
    keywords: "스마트베타ETF,팩터ETF,초과수익",
    meta_description: "단순 시장 추종이 아닌 특정 팩터를 가중한 스마트 베타 ETF로 알파를 추구하는 방법.",
  },
  {
    index: 109, slug: "adv-023", level: "고급편", category: "after",
    title: "자산관리 성과 측정: 샤프지수, 트레이너지수 이해",
    keywords: "샤프지수,트레이너지수,포트폴리오성과",
    meta_description: "내 포트폴리오가 위험 대비 얼마나 좋은 성과를 내고 있는지 측정하는 지표.",
  },
  {
    index: 110, slug: "adv-024", level: "고급편", category: "tax",
    title: "법인을 통한 투자: 개인 vs 법인 세금 비교",
    keywords: "법인투자,개인vs법인,투자법인설립",
    meta_description: "투자 소득이 많아지면 개인보다 법인으로 투자하는 것이 유리한 시점과 세금 비교.",
  },
  {
    index: 111, slug: "adv-025", level: "고급편", category: "tax",
    title: "해외 계좌 신고 의무: 해외금융계좌 신고 완전 정리",
    keywords: "해외계좌신고,해외금융계좌,FATCA",
    meta_description: "해외 금융계좌 잔고가 5억원 이상이면 신고 의무가 발생합니다. 신고 방법과 미신고 시 불이익.",
  },
  {
    index: 112, slug: "adv-026", level: "고급편", category: "tax",
    title: "가업 승계 절세 전략: 사업체 물려줄 때 세금 줄이기",
    keywords: "가업승계,가업상속공제,가업증여",
    meta_description: "가업을 자녀에게 물려줄 때 적용되는 가업상속공제, 가업증여 특례 활용 전략.",
  },
  {
    index: 113, slug: "adv-027", level: "고급편", category: "tax",
    title: "신탁을 활용한 자산 관리: 세금과 상속의 교차점",
    keywords: "신탁,재산신탁,자산관리신탁",
    meta_description: "신탁 제도를 활용해 자산을 관리하고 상속 과정에서 세금을 절감하는 방법.",
  },
  {
    index: 114, slug: "adv-028", level: "고급편", category: "tax",
    title: "손실 이월공제: 투자 손실을 세금으로 환급받는 방법",
    keywords: "손실이월공제,세금환급,손실공제",
    meta_description: "투자에서 손실이 났을 때 이를 이월해 미래의 양도소득세를 줄이는 방법.",
  },
  {
    index: 115, slug: "adv-029", level: "고급편", category: "tax",
    title: "고액 자산가의 절세 전략: 세금 없는 부자들의 비밀",
    keywords: "절세전략,고액자산가,절세설계",
    meta_description: "자산이 많을수록 더 중요해지는 체계적 절세 전략과 법적으로 허용된 절세 방법.",
  },
  {
    index: 116, slug: "adv-030", level: "고급편", category: "law",
    title: "자본시장법 핵심: 투자자 보호 규정의 실제 적용",
    keywords: "자본시장법,투자자보호,금융규제",
    meta_description: "자본시장법이 투자자를 어떻게 보호하는지, 실제 분쟁에서 어떻게 활용할 수 있는지.",
  },
  {
    index: 117, slug: "adv-031", level: "고급편", category: "law",
    title: "해외 투자 규정: 외국환거래법 핵심 이해",
    keywords: "외국환거래법,해외투자규정,해외송금",
    meta_description: "해외 투자 시 반드시 알아야 할 외국환거래법 규정과 신고 의무.",
  },
  {
    index: 118, slug: "adv-032", level: "고급편", category: "law",
    title: "집합투자기구(펀드) 규정: 운용사 선택 시 확인 사항",
    keywords: "펀드규정,집합투자기구,운용사선택",
    meta_description: "펀드 투자 전 확인해야 할 법적 사항과 좋은 운용사를 선택하는 기준.",
  },
  {
    index: 119, slug: "adv-033", level: "고급편", category: "law",
    title: "부동산 규제 변화와 투자 전략: 정책 리스크 관리",
    keywords: "부동산규제,투자규제,정책리스크",
    meta_description: "정부의 부동산 규제 변화에 따른 투자 전략 수정과 정책 리스크를 관리하는 방법.",
  },
  {
    index: 120, slug: "adv-034", level: "고급편", category: "law",
    title: "투자 계약서 법적 효력: 분쟁 발생 시 권리 주장법",
    keywords: "투자계약서,법적효력,투자분쟁",
    meta_description: "투자 관련 계약서의 법적 효력과 분쟁 발생 시 권리를 주장하는 방법.",
  },
  {
    index: 121, slug: "adv-035", level: "고급편", category: "ai",
    title: "머신러닝으로 주가 예측: 가능성과 한계",
    keywords: "머신러닝주가예측,AI주가예측,딥러닝투자",
    meta_description: "머신러닝 모델로 주가를 예측하는 것이 얼마나 가능한지, 실제 성과와 한계.",
  },
  {
    index: 122, slug: "adv-036", level: "고급편", category: "ai",
    title: "AI 기반 포트폴리오 최적화: 알고리즘 자산 배분",
    keywords: "AI포트폴리오최적화,알고리즘자산배분,AI투자",
    meta_description: "AI 알고리즘을 활용해 리스크 대비 최적의 수익을 내는 포트폴리오를 구성하는 방법.",
  },
  {
    index: 123, slug: "adv-037", level: "고급편", category: "ai",
    title: "자연어처리(NLP)로 공시 분석: 투자 신호 자동 탐지",
    keywords: "NLP공시분석,텍스트마이닝,투자신호탐지",
    meta_description: "NLP 기술을 활용해 기업 공시문서에서 투자 신호를 자동으로 찾아내는 방법.",
  },
  {
    index: 124, slug: "adv-038", level: "고급편", category: "ai",
    title: "GPT-4를 활용한 기업 분석: 사업보고서 요약과 인사이트",
    keywords: "GPT기업분석,AI사업보고서,AI투자분석",
    meta_description: "GPT-4로 수백 페이지의 사업보고서를 빠르게 요약하고 투자 인사이트를 추출하는 방법.",
  },
  {
    index: 125, slug: "adv-039", level: "고급편", category: "ai",
    title: "AI 시대 투자자의 역할: 인간과 알고리즘의 협업",
    keywords: "AI투자자역할,인간AI협업,AI시대투자",
    meta_description: "AI가 투자 시장을 어떻게 변화시키고 있으며 인간 투자자가 AI와 어떻게 협업해야 하는지.",
  },
  {
    index: 126, slug: "adv-040", level: "고급편", category: "ai",
    title: "블록체인과 토큰 투자: 디지털 자산의 현재와 미래",
    keywords: "블록체인투자,토큰투자,디지털자산",
    meta_description: "블록체인 기반 디지털 자산의 현재 상황과 전통 포트폴리오에 편입 시 고려 사항.",
  },
  {
    index: 127, slug: "adv-041", level: "고급편", category: "before",
    title: "패시브 vs 액티브 투자: 장기 성과 비교 연구",
    keywords: "패시브투자,액티브투자,인덱스펀드",
    meta_description: "수십 년간의 데이터로 보는 패시브(인덱스) 투자와 액티브(종목 선정) 투자의 성과 비교.",
  },
  {
    index: 128, slug: "adv-042", level: "고급편", category: "bidding",
    title: "이머징마켓 투자: 신흥국 ETF의 기회와 위험",
    keywords: "신흥국투자,이머징마켓,EM ETF",
    meta_description: "중국, 인도, 베트남 등 신흥국 시장에 투자하는 방법과 높은 수익률이 수반하는 위험.",
  },
  {
    index: 129, slug: "adv-043", level: "고급편", category: "after",
    title: "부의 복리 효과: 10억을 만드는 30년 시나리오",
    keywords: "부의복리,10억만들기,장기복리시나리오",
    meta_description: "매달 100만원씩 30년간 투자하면 얼마가 될까? 수익률별 자산 성장 시뮬레이션.",
  },
  {
    index: 130, slug: "adv-044", level: "고급편", category: "ai",
    title: "투자 자동화 시스템 구축: AI와 함께하는 포트폴리오 관리",
    keywords: "투자자동화,AI포트폴리오관리,자동리밸런싱",
    meta_description: "AI와 자동화 도구를 활용해 감정 없이 원칙대로 투자하는 자동화 시스템 구축 방법.",
  },
];
